name: Go Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unix-tests:
    name: Unix Tests
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.20', '1.21']
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.CI_AWS_ACCOUNT_ID }}:role/${{ vars.CI_AWS_ROLE }}
        role-session-name: S3EC-Github-Go-CI-Tests
        aws-region: ${{ vars.CI_AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Go Test
      run: |
        cd client
        export AWS_REGION=${{ vars.CI_AWS_REGION }}
        export BUCKET=${{ vars.CI_S3_BUCKET }}
        export AWS_KMS_ALIAS=${{ vars.CI_KMS_KEY_ALIAS }}
        export AWS_ACCOUNT_ID=${{ secrets.CI_AWS_ACCOUNT_ID }}
        go test *.go -v
        cd ../internal
        export AWS_REGION=${{ vars.CI_AWS_REGION }}
        export BUCKET=${{ vars.CI_S3_BUCKET }}
        export AWS_KMS_ALIAS=${{ vars.CI_KMS_KEY_ALIAS }}
        export AWS_ACCOUNT_ID=${{ secrets.CI_AWS_ACCOUNT_ID }}
        go test *.go -v

    # TODO: remove after public launch
    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.REPO_PAT_JUSTPLAZ }}
      run: git config --global url."https://justplaz:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Test Vectors
      run: |
        cd testvectors
        export AWS_REGION=${{ vars.CI_AWS_REGION }}
        export BUCKET=${{ vars.CI_S3_BUCKET }}
        export AWS_KMS_ALIAS=${{ vars.CI_KMS_KEY_ALIAS }}
        export AWS_ACCOUNT_ID=${{ secrets.CI_AWS_ACCOUNT_ID }}
        go test *.go -v
